version: '3.8'
services:
  db:
    build: .
    container_name: docker-springboot
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3305:3304
    volumes:
      - $PWD/sql:/docker-entrypoint-initdb.d
